spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

jwt:
  secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  expire-length: 3600000

springdoc:
  swagger-ui:
    path: /api-docs
    docExpansion: list
    operationsSorter: method
    defaultModelsExpandDepth: 0
    defaultModelRendering: example

roomescape:
  payment:
    toss:
      connection-timeout-duration-of-second: 5
      read-timeout-duration-of-second: 30
      confirm-endpoint-v1: "/v1/payments/confirm"
      confirm-widget-secret-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"
      confirm-password: ""
